# Generated by Django 6.0.3 on 2026-04-08 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('prefijo', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_caja', to='cajas.empresa')),
            ],
            options={
                'verbose_name': 'Tipo de caja',
                'verbose_name_plural': 'Tipos de caja',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SecuenciaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuencias_caja', to='cajas.empresa')),
                ('tipo_caja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='secuencia', to='cajas.tipocaja')),
            ],
            options={
                'verbose_name': 'Secuencia de caja',
                'verbose_name_plural': 'Secuencias de caja',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('correlativo', models.PositiveIntegerField(default=0, editable=False)),
                ('tecnico', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='cajas.empresa')),
                ('tipo_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cajas', to='cajas.tipocaja')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='cajas.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_empresa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de empresa',
                'verbose_name_plural': 'Usuarios de empresa',
            },
        ),
        migrations.AddConstraint(
            model_name='tipocaja',
            constraint=models.UniqueConstraint(fields=('empresa', 'nombre'), name='uq_tipo_nombre_empresa'),
        ),
        migrations.AddConstraint(
            model_name='tipocaja',
            constraint=models.UniqueConstraint(fields=('empresa', 'prefijo'), name='uq_tipo_prefijo_empresa'),
        ),
        migrations.AddConstraint(
            model_name='secuenciacaja',
            constraint=models.UniqueConstraint(fields=('empresa', 'tipo_caja'), name='uq_secuencia_empresa_tipo'),
        ),
        migrations.AddConstraint(
            model_name='caja',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='uq_codigo_empresa'),
        ),
    ]
